spring.datasource.url=${DB_URL:jdbc:mariadb://localhost:1034/inventory_db?createDatabaseIfNotExist=true}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:root123}

spring.jpa.show-sql=true

spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}

logstash.host=${LOGSTASH_HOST:localhost}
logstash.port=${LOGSTASH_PORT:5000}

app.jwt.secret=${JWT_SECRET:c3VwZXItc2VjcmV0LWtleS1mb3ItaW52ZW50b3J5LXBsYXRmb3JtLWNoYW5nZS1pbi1wcm9kdWN0aW9uLTI1Ng==}

logging.level.com.csj.inventory=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE
